services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - /data/elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: ${NEXUS_NODE_NAME}
      node.roles: ${NEXUS_NODE_ROLES}
      network.publish_host: ${NEXUS_NODE_IP}
      transport.publish_host: ${NEXUS_NODE_IP}
      http.publish_host: ${NEXUS_NODE_IP}
      discovery.seed_hosts: nexus-master-1,nexus-worker-1,nexus-worker-2,nexus-worker-3,nexus-worker-4
      cluster.initial_master_nodes: nexus-master-1
      ES_JAVA_OPTS: "${ES_JAVA_OPTS:--Xms4g -Xmx4g}"
    networks:
      - elk
    restart: unless-stopped

  postgres:
    profiles:
      - master
    image: postgres:16-bookworm
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - /data/postgres:/var/lib/postgresql/data:Z
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - elk
    restart: unless-stopped

  kibana:
    profiles:
      - master
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  elk:
    driver: bridge
